// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FadingController from "./fading_controller"
application.register("fading", FadingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LazyLoaderController from "./lazy_loader_controller"
application.register("lazy-loader", LazyLoaderController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
