// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LazyLoaderController from "./lazy_loader_controller"
application.register("lazy-loader", LazyLoaderController)

import PersistCheckedController from "./persist_checked_controller"
application.register("persist-checked", PersistCheckedController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import { initSortable } from "./sortable"
initSortable()

import TomsNo2Controller from "./toms_no2_controller"
application.register("toms-no2", TomsNo2Controller)
